spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/airtrackmp}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: airtrack-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

server:
  port: ${PORT:8080}

jwt:
  secret: airtrackmpsecretkeyairtrackmpsecretkey123456

ml:
  service:
    url: ${ML_SERVICE_URL:http://localhost:5000}

logging:
  level:
    org.springframework.security: DEBUG
